version: '3.3'

services:
  dbgpt:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "54321:5432"
    restart: always
    networks:
      - tg_bot_gpt

  botgpt:
    # image: "${BOT_IMAGE_NAME:-tg_bot-image}"
    # container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
    stop_signal: SIGINT
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: "/usr/src/app/${BOT_NAME:-tg_bot}"
    volumes:
    - .:/usr/src/app/${BOT_NAME:-tg_bot}
    command: >
      sh -c "python3 -m bot"
    restart: always
    env_file:
      - ".env"
    networks:
    - tg_bot_gpt
    depends_on:
      - dbgpt

  # redis:
  #   container_name: redis-bot
  #   image: redis:5-alpine
  #   restart: always
  #   env_file:
  #     - .env
  #   ports:
  #     - ${REDIS_PORT}:${REDIS_PORT}
  #   expose:
  #     - ${REDIS_PORT}
  #   volumes:
  #     - ./redis_data:/data
  #   networks:
  #     - tg_bot

networks:
  tg_bot_gpt:
    driver: bridge